# Importing Libraries

In [207]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing Dataset

In [208]:
dataset = pd.read_csv('data.csv', sep=';')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [209]:
print(len(y))

4424


In [210]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,3,5,7,8,9,10,11])], remainder='passthrough')
X = ct.fit_transform(X).toarray()

In [211]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# Splitting the data into training and test set

In [212]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [213]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [214]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

# Logistic Regression

In [215]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [216]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[223  29  32]
 [ 38  58  55]
 [ 17  28 405]]
0.7751412429378531


In [217]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X = X_train, y=y_train, cv=10)
print(f"Accuracy: {accuracies.mean()*100}%")
print(f"Standard Deviation: {accuracies.std()*100}")

Accuracy: 79.73976088730974%
Standard Deviation: 1.3709819617893295


In [218]:
from sklearn.model_selection import GridSearchCV
parameters = [{
    'penalty': ['l1', 'l2'],  # Regularization penalty
    'C': [0.001, 0.01, 0.1, 1, 10, 100],  # Inverse of regularization strength
    'solver': ['liblinear', 'saga'],  # Solver algorithm
    'max_iter': [100, 200, 300],  # Maximum number of iterations
}]
grid_search = GridSearchCV(estimator = classifier,param_grid = parameters,scoring = 'accuracy',cv = 10,n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 79.77 %
Best Parameters: {'C': 1, 'max_iter': 100, 'penalty': 'l1', 'solver': 'saga'}
